// Created by iWeb 3.0.1 local-build-20100809

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({shadow_0:new IWShadow({blurRadius:10,offset:new IWPoint(-1.0419,5.9088),color:'#b3b3b3',opacity:0.750000}),stroke_0:new IWPhotoFrame([IWCreateImage('Links_files/Watercolor_iweb_01.png'),IWCreateImage('Links_files/Watercolor_iweb_02.png'),IWCreateImage('Links_files/Watercolor_iweb_04.png'),IWCreateImage('Links_files/Watercolor_iweb_08.png'),IWCreateImage('Links_files/Watercolor_iweb_16.png'),IWCreateImage('Links_files/Watercolor_iweb_14.png'),IWCreateImage('Links_files/Watercolor_iweb_13.png'),IWCreateImage('Links_files/Watercolor_iweb_05.png')],null,0,0.800000,0.000000,0.000000,0.000000,0.000000,12.000000,12.000000,11.000000,11.000000,13.000000,12.000000,13.000000,12.000000,null,null,null,0.500000)});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Links_files/LinksMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');fixupAllIEPNGBGs();fixAllIEPNGs('Media/transparent.gif');IMpreload('Links_files','shapeimage_1','0');IMpreload('Links_files','shapeimage_1','1');IMpreload('Links_files','shapeimage_1','2');IMpreload('Links_files','shapeimage_1','3');IMpreload('Links_files','shapeimage_1','4');IMpreload('Links_files','shapeimage_1','5');IMpreload('Links_files','shapeimage_1','6');IMpreload('Links_files','shapeimage_1','7');IMpreload('Links_files','shapeimage_1','8');IMpreload('Links_files','shapeimage_1','9');IMpreload('Links_files','shapeimage_1','10');IMpreload('Links_files','shapeimage_1','11');IMpreload('Links_files','shapeimage_1','12');IMpreload('Links_files','shapeimage_1','13');IMpreload('Links_files','shapeimage_1','14');IMpreload('Links_files','shapeimage_1','15');IMpreload('Links_files','shapeimage_1','16');IMpreload('Links_files','shapeimage_1','17');IMpreload('Links_files','shapeimage_1','18');IMpreload('Links_files','shapeimage_1','19');IMpreload('Links_files','shapeimage_1','20');IMpreload('Links_files','shapeimage_1','21');IMpreload('Links_files','shapeimage_1','22');IMpreload('Links_files','shapeimage_1','23');IMpreload('Links_files','shapeimage_1','24');applyEffects()}
